### ISSUE TITLE
TargetFramework

### ISSUE THREAD

**Issue by paulober** [DjordjeNedovic/Advent-of-Code#1]
Why do you use <TargetFramework>netcoreapp3.0</TargetFramework> instead of the newer one: <TargetFramework>netcoreapp3.1</TargetFramework> or the newest: <TargetFramework>net5.0</TargetFramework>?

**Comment by DjordjeNedovic** [comment]
To be honest, version 3.0 I choose last year for AoC 2019 and just continue with the same strategy for this one. Also, I don't see any benefit of using 3.1 and how it will help me with solving puzzles.
